#!/bin/bash

echo 1

head -n1 logs/1.memory.log | cut -d" " -f1 | grep -o '[0-9]*'

echo 2

grep -v '^\s*$' "tests.lst" | cut -d"@" -f3 | uniq | sort

echo 3

grep -m 1 "hello" ./logs/*.inout.log | uniq | wc -l

echo 4

ls -r ./logs/*.inout.log --sort=time | tail -n1 | cut -c 3-

echo 5

ls -r ./logs/*.inout.log | sort -n | tail -n1 | cut -c 3-
